<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>041-await的使用.html</title>
</head>
<body>
	
</body>
<script>
    /*
    //1.await表示后面的处理需要等待,通常await后面是一个 Promise 对象,返回该对象的结果。如果不是Promise对象,就直接返回对应的值。
    //2.await命令后面的Promise对象如果变为reject状态,程序中止,reject的参数会被catch方法的回调函数接收到。
    async function fn(){
        const data1 = await 'data1'

        console.log('data1:::',data1);

        const data2 = await 'data2 ...'

        // console.log('do something...');

        return data2
    }
    fn()
    .then(data=>{
        console.log(data);
    })
    */


    /*
    const promise = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            resolve('success data');
        },200);
    })

    async function fn(){
        const data1 = await promise

        console.log('data1=',data1);

        return data1;        
    }
    fn()
    .then(data=>{
        console.log(data);
    })
    */
    
    
    const promise = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            reject('reject data');
        },200);
    })

    //try...catch防止出错的方法。
    async function fn(){
        try{//防止出错的方法，是await语句放在try...catch代码块之中。
            const data1 = await promise 
            console.log('get data1=',data1);
            console.log('do something...');
        }catch(err){
            console.log('err=',err);
        }
        
        return 'result data ...'        
    }
    fn()
    .then(data=>{
        console.log(data);
    })


</script>
</html>